#!/bin/bash

index=0
while read line; do
    array[$index]="$line"
    index=$(($index+1))
done < /home/sinegubov/ip_SIB

for ((a=0; a < ${#array[*]}; a++))
do
    b=$(cat /home/sinegubov/dhcpd_03022021.log | grep "DHCPACK on ${array[$a]}")
    if [ -n "$b" ]
    	then echo "${array[$a]} DHCP" >> /home/sinegubov/dhcp_itog2
    #else 
    	#echo " " >> /home/sinegubov/dhcp_itog2
    fi
done 

